content:
  - name: posts
    label: 网页预览修改
    type: collection
    path: post       # 对应你截图里的 post 文件夹
    format: html     # 因为你现在仓库里全是 html
    fields:
      - name: body
        label: 内容
        type: rich-text